/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsExports = {
  aws_project_region: "eu-central-1",
  aws_cognito_identity_pool_id: "",
  aws_cognito_region: "eu-central-1",
  aws_user_pools_id: "eu-central-1_Aqadja7f9",
  aws_user_pools_web_client_id: "1orgjk83egbvgdja2kmcgh0sor",
  oauth: {
    domain: "rafet-dashboard.auth.eu-central-1.amazoncognito.com",
    scope: [
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
      "phone",
    ],
    redirectSignIn:
      "http://localhost:5173/,https://d3o0qmvpbmut8f.cloudfront.net/",
    redirectSignOut:
      "http://localhost:5173/,https://d3o0qmvpbmut8f.cloudfront.net/",
    responseType: "token",
    // redirectSignIn: ["http://localhost:5173/"],
    // redirectSignOut: ["http://localhost:5173/"],
  },
  aws_cognito_username_attributes: ["EMAIL"],
  aws_cognito_social_providers: [],
  aws_cognito_signup_attributes: ["EMAIL", "USERNAME"],
  aws_cognito_mfa_configuration: "OFF",
  aws_cognito_mfa_types: ["SMS"],
  aws_cognito_password_protection_settings: {
    passwordPolicyMinLength: 8,
    passwordPolicyCharacters: [],
  },
  aws_cognito_verification_mechanisms: ["EMAIL"],
};

export default awsExports;
